export type EkycSdkConfig = {
    BACKEND_URL: string;
    TOKEN_KEY: string;
    TOKEN_ID: string;
    ACCESS_TOKEN?: string;
    HAS_RESULT_SCREEN?: boolean;
    CALL_BACK_END_FLOW: (result: any) => void;
    ENABLE_API_LIVENESS_DOCUMENT?: boolean;
    ENABLE_API_LIVENESS_FACE?: boolean;
    ENABLE_API_MASKED_FACE?: boolean;
    ENABLE_API_COMPARE_FACE?: boolean;
    SDK_FLOW?: 'DOCUMENT_TO_FACE' | 'FACE_TO_DOCUMENT' | 'FACE' | 'DOCUMENT';
    LIST_TYPE_DOCUMENT?: number[];
    CUSTOM_THEME?: {
        PRIMARY_COLOR?: string;
        TEXT_COLOR_DEFAULT?: string;
        BACKGROUND_COLOR?: string;
    };
    CHALLENGE_CODE?: string;
    SHOW_STEP?: boolean;
    HAS_QR_SCAN?: boolean;
    DOCUMENT_TYPE_START?: number;
    DEFAULT_LANGUAGE?: 'vi' | 'en';
    DOUBLE_LIVENESS?: boolean;
    FAKE_CAM_LABEL?: string | RegExp;
    CALL_BACK_DOCUMENT_RESULT?: (result: any) => Promise<void>;
    LINK_ICON_CCCD?: string;
    LINK_ICON_PASSPORT?: string;
    LINK_ICON_DRIVER_LICENSE?: string;
    LINK_ICON_OTHER_PAPERS?: string;
    LINK_ICON_QR_SCAN?: string;
    HAS_BACKGROUND_IMAGE?: boolean;
    USE_METHOD?: 'BOTH' | 'PHOTO' | 'UPLOAD';
    SHOW_TAB_RESULT_INFORMATION?: boolean;
    SHOW_TAB_RESULT_VALIDATION?: boolean;
    SHOW_TAB_RESULT_QRCODE?: boolean;
    URL_WEB_OVAL?: string;
    URL_MOBILE_OVAL?: string;
    URL_ENGLISH_VIDEO_TUTORIAL?: string;
    URL_VIETNAMESE_VIDEO_TUTORIAL?: string;
    MAX_SIZE_IMAGE?: number;
    ENDPOINT_UPLOAD_IMAGE?: string;
    ENDPOINT_LIVENESS_DOCUMENT?: string;
    ENDPOINT_LIVENESS_FACE?: string;
    ENDPOINT_MASKED_FACE?: string;
    ENDPOINT_COMPARE_FACE?: string;
    ENDPOINT_OCR_DOCUMENT?: string;
    ENDPOINT_OCR_DOCUMENT_FRONT?: string;
    ENABLE_API_UPLOAD_IMAGE?: boolean;
    ENABLE_API_OCR_DOCUMENT?: boolean;
    ENABLE_API_OCR_DOCUMENT_FRONT?: boolean;
};